/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  phoneNumber?: string;
  email?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: Array<{
    platform?:
      | "facebook"
      | "instagram"
      | "twitter"
      | "linkedin"
      | "youtube"
      | "tiktok";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  address?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Promo = {
  _id: string;
  _type: "promo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: string;
  isActive?: boolean;
  startDate?: string;
  endDate?: string;
  ctaText?: string;
  ctaUrl?: string;
  targetPages?: Array<
    | "homepage"
    | "holo-pro"
    | "holo-mini"
    | "holo-active"
    | "checkout"
    | "savings-program"
    | "referral-program"
    | "general"
  >;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: string;
  role?: string;
  location?: string;
  rating?: number;
  date?: string;
  productSlug?: "holo-pro" | "holo-mini" | "holo-active";
  isApproved?: boolean;
  webflowId?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  pages?: Array<
    | "homepage"
    | "holo-pro"
    | "holo-mini"
    | "holo-active"
    | "checkout"
    | "savings-program"
    | "referral-program"
    | "general"
  >;
  category?:
    | "device-specific"
    | "billing"
    | "monitoring"
    | "shipping"
    | "general";
  sortOrder?: number;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  author?: string;
  category?: string;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  isFeatured?: boolean;
  seoTitle?: string;
  webflowId?: string;
};

export type Device = {
  _id: string;
  _type: "device";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featuresImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  monthlyPriceDisplay?: string;
  annualPriceDisplay?: string;
  devicePrice?: number;
  reducedDevicePrice?: number;
  stripePriceIdMonthly?: string;
  stripePriceIdYearly?: string;
  stripePriceIdDevice?: string;
  specs?: Array<{
    label?: string;
    value?: string;
    _type: "spec";
    _key: string;
  }>;
  features?: Array<{
    title?: string;
    content?: string;
    _type: "feature";
    _key: string;
  }>;
  howItWorksSteps?: Array<{
    content?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
  accessories?: Array<{
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "accessory";
    _key: string;
  }>;
  videoUrl?: string;
  videoThumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  pricingCardSubhead?: string;
  pricingCardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  pricingCardOrder?: number;
  pricingCardSubscription?: string;
  pricingCardBenefits?: Array<string>;
  fallAlertDisclaimer?: string;
  shippingTimeline?: string;
  isActive?: boolean;
  webflowId?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Promo
  | Testimonial
  | Slug
  | Faq
  | BlogPost
  | Device
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{ siteTitle, phoneNumber, email, socialLinks, address }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteTitle: string | null;
  phoneNumber: string | null;
  email: string | null;
  socialLinks: Array<{
    platform?:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "tiktok"
      | "twitter"
      | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  address: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: DEVICES_QUERY
// Query: *[_type == "device" && isActive == true] | order(pricingCardOrder asc) {    _id, name, slug, tagline, monthlyPriceDisplay, annualPriceDisplay,    devicePrice, reducedDevicePrice, pricingCardImage, pricingCardSubhead,    pricingCardSubscription, pricingCardBenefits, pricingCardOrder  }
export type DEVICES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  tagline: string | null;
  monthlyPriceDisplay: string | null;
  annualPriceDisplay: string | null;
  devicePrice: number | null;
  reducedDevicePrice: number | null;
  pricingCardImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  pricingCardSubhead: string | null;
  pricingCardSubscription: string | null;
  pricingCardBenefits: Array<string> | null;
  pricingCardOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: DEVICE_QUERY
// Query: *[_type == "device" && slug.current == $slug][0] {    _id, name, slug, tagline, description, mainImage, featuresImage, gallery,    monthlyPriceDisplay, annualPriceDisplay, devicePrice, reducedDevicePrice,    stripePriceIdMonthly, stripePriceIdYearly, stripePriceIdDevice,    specs, features, howItWorksSteps, accessories,    videoUrl, videoThumbnail, fallAlertDisclaimer, shippingTimeline,    pricingCardSubhead, pricingCardImage, pricingCardOrder,    pricingCardSubscription, pricingCardBenefits, isActive  }
export type DEVICE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  featuresImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  monthlyPriceDisplay: string | null;
  annualPriceDisplay: string | null;
  devicePrice: number | null;
  reducedDevicePrice: number | null;
  stripePriceIdMonthly: string | null;
  stripePriceIdYearly: string | null;
  stripePriceIdDevice: string | null;
  specs: Array<{
    label?: string;
    value?: string;
    _type: "spec";
    _key: string;
  }> | null;
  features: Array<{
    title?: string;
    content?: string;
    _type: "feature";
    _key: string;
  }> | null;
  howItWorksSteps: Array<{
    content?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }> | null;
  accessories: Array<{
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "accessory";
    _key: string;
  }> | null;
  videoUrl: string | null;
  videoThumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  fallAlertDisclaimer: string | null;
  shippingTimeline: string | null;
  pricingCardSubhead: string | null;
  pricingCardImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  pricingCardOrder: number | null;
  pricingCardSubscription: string | null;
  pricingCardBenefits: Array<string> | null;
  isActive: boolean | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc) [0...12] {    _id, title, slug, publishedAt, author, category, excerpt, mainImage, isFeatured  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: string | null;
  category: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  isFeatured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id, title, slug, publishedAt, author, category, excerpt, mainImage, heroImage, body, seoTitle  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: string | null;
  category: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq" && $page in pages] | order(sortOrder asc) {    _id, question, answer, category, sortOrder  }
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  question: string | null;
  answer: string | null;
  category:
    | "billing"
    | "device-specific"
    | "general"
    | "monitoring"
    | "shipping"
    | null;
  sortOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && isApproved == true] | order(date desc) {    _id, name, body, role, location, rating, date, productSlug  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  body: string | null;
  role: string | null;
  location: string | null;
  rating: number | null;
  date: string | null;
  productSlug: "holo-active" | "holo-mini" | "holo-pro" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ACTIVE_PROMO_QUERY
// Query: *[_type == "promo" && isActive == true    && (startDate == null || startDate <= now())    && (endDate == null || endDate >= now())  ][0] { _id, title, body, ctaText, ctaUrl, targetPages }
export type ACTIVE_PROMO_QUERY_RESULT = {
  _id: string;
  title: string | null;
  body: string | null;
  ctaText: string | null;
  ctaUrl: string | null;
  targetPages: Array<
    | "checkout"
    | "general"
    | "holo-active"
    | "holo-mini"
    | "holo-pro"
    | "homepage"
    | "referral-program"
    | "savings-program"
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{ siteTitle, phoneNumber, email, socialLinks, address }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "device" && isActive == true] | order(pricingCardOrder asc) {\n    _id, name, slug, tagline, monthlyPriceDisplay, annualPriceDisplay,\n    devicePrice, reducedDevicePrice, pricingCardImage, pricingCardSubhead,\n    pricingCardSubscription, pricingCardBenefits, pricingCardOrder\n  }': DEVICES_QUERY_RESULT;
    '*[_type == "device" && slug.current == $slug][0] {\n    _id, name, slug, tagline, description, mainImage, featuresImage, gallery,\n    monthlyPriceDisplay, annualPriceDisplay, devicePrice, reducedDevicePrice,\n    stripePriceIdMonthly, stripePriceIdYearly, stripePriceIdDevice,\n    specs, features, howItWorksSteps, accessories,\n    videoUrl, videoThumbnail, fallAlertDisclaimer, shippingTimeline,\n    pricingCardSubhead, pricingCardImage, pricingCardOrder,\n    pricingCardSubscription, pricingCardBenefits, isActive\n  }': DEVICE_QUERY_RESULT;
    '*[_type == "blogPost"] | order(publishedAt desc) [0...12] {\n    _id, title, slug, publishedAt, author, category, excerpt, mainImage, isFeatured\n  }': BLOG_POSTS_QUERY_RESULT;
    '*[_type == "blogPost" && slug.current == $slug][0] {\n    _id, title, slug, publishedAt, author, category, excerpt, mainImage, heroImage, body, seoTitle\n  }': BLOG_POST_QUERY_RESULT;
    '*[_type == "faq" && $page in pages] | order(sortOrder asc) {\n    _id, question, answer, category, sortOrder\n  }': FAQS_QUERY_RESULT;
    '*[_type == "testimonial" && isApproved == true] | order(date desc) {\n    _id, name, body, role, location, rating, date, productSlug\n  }': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "promo" && isActive == true\n    && (startDate == null || startDate <= now())\n    && (endDate == null || endDate >= now())\n  ][0] { _id, title, body, ctaText, ctaUrl, targetPages }': ACTIVE_PROMO_QUERY_RESULT;
  }
}
